### ISSUE TITLE
Set operation names and masking

### ISSUE THREAD

**Issue by RaphaelS1** [RaphaelS1/set6#10]
Currently set operator names copy the names of base, i.e. `union, intersect, setdiff` (although `setequal` -> `equal`). Whilst the user will get a message saying these are masked on loading of `set6` this is not actually true as I have used S3 dispatch to call the `base` functions if the objects are not R6 classes, i.e. in pseudo-code

```R
union = function(x, y){
 if(!inherit(x, "R6"))
  base::union(x, y)
else
  UseMethod("union")
}
```

Despite this, is it still better to re-name operations to something like `union -> setunion` (although `setsetdiff` may look strange)

**Comment by fkiraly** [comment]
I'm still not too happy with the override, since obviously it works only *once*, i.e., at most one package can do this. Loosely citing Immanuel Kant, best programming practice is only what can be simultaneously applied to all packages...

**Comment by fkiraly** [comment]
So, what about `Union` and `Setdiff`? Or `union6` and `setdiff6`?

**Comment by fkiraly** [comment]
Or `uni6n` and `set6iff`?

**Comment by RaphaelS1** [comment]
Changed as follows:

* complement (method) -> absComplement
* setdiff (function) -> setcomplement
* DifferenceSet (class) -> ComplementSet
* symdiff (function) - unchanged

* intersect (function) -> setintersect

* power_set (function) -> powerset
* Powerset (class) -> PowersetSet

* power (function) - unchanged
* ExponentSet - unchanged
* product (function) -> setproduct
* ProductSet (class) - unchanged

* union (function) -> setunion
* UnionSet (class) - unchanged
