### ISSUE TITLE
Union cardinality calculation error

### ISSUE THREAD

**Issue by RaphaelS1** [RaphaelS1/set6#40]
The cardinality of UnionSet is currently calculated as

|A| + |B|

for two sets A,B. It should be

|A| + |B| - |A and B|

**Comment by fkiraly** [comment]
... unless some of the are infinite, in which case a careful case distinctin might be necessary?

**Comment by RaphaelS1** [comment]
Do you mean in case A or B are infinite? In which case the corresponding Aleph of Beth number is used automatically

**Comment by fkiraly** [comment]
Yes, but they don’t sum like that.
What you get is the largest of the aleph/beth of the two in union; in intersection, you don’t know (can be anything).
